### ISSUE TITLE
Inadequate setup documentation 

### ISSUE THREAD

**Issue by mLuby** [matthijsgroen/chai-backbone#7]
There are no setup instructions or full use examples available here or elsewhere online.

It's probably a very simple answer, but completely prevented us from using this library (which would have been a perfect fit for our needs).

Thanks!

**Comment by hyprstack** [comment]
Same here. Also having trouble with the same issue.

**Comment by hyprstack** [comment]
Would also help if you could provide examples that are not in coffee-script. It might be confusing for any novice developer who might come across your plugin.

**Comment by matthijsgroen** [comment]
Could the test file in `test/browser/index.html` be of any help?

**Comment by hyprstack** [comment]
Yeap. It helps! Cheers!

**Comment by mLuby** [comment]
@hyprstack I'm fine with closing this comment if you think it's resolved.

**Comment by hyprstack** [comment]
@mLuby Yes sir :+1:
